### ISSUE TITLE
Spacing on quote block has regressed 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#306] opened 2024-07-18 16:04 UTC
https://www.amnesty.org/es/latest/news/2024/07/peru-muertes-lesiones-protestas-presidenta-cadena-mando-responsables-penales/

![image](https://github.com/user-attachments/assets/6a8b9b78-2f5d-4588-9a7b-c4c7737e40ab)

should look more like this 

![image](https://github.com/user-attachments/assets/5c467a90-d22b-4073-bc37-464fe700bd0a)

**Comment by jaymcp** [comment] 2024-07-19 10:55
duplicate of https://github.com/amnestywebsite/humanity-theme/issues/294

**Closed** 2024-07-23 12:27 UTC
Labels: bug
