### ISSUE TITLE
Bug - alt text field on featured image no longer editable in CMS

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#308] opened 2024-07-18 16:08 UTC
when you select the box, you are not able to get a curser and type into the box 

![image](https://github.com/user-attachments/assets/fee8e07a-3799-48c4-8a32-4e43fd87b540)

**Comment by jaymcp** [comment] 2024-07-19 10:55
duplicate of https://github.com/amnestywebsite/humanity-theme/issues/302

**Closed** 2024-08-20 14:49 UTC
Labels: bug
