### ISSUE TITLE
Bug - Theme option to add google font is missing 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#305] opened 2024-07-17 11:52 UTC
**Describe the bug**  
Theme option to add google font is missing 

**To Reproduce**  
1. Go to theme options
2. Look for font tab
3. See it is missing

**Expected behaviour**  
![image](https://github.com/user-attachments/assets/5f615101-9960-4025-8d6b-0243ac738cc0)

**Actual behaviour**  
![image](https://github.com/user-attachments/assets/39f09cdf-7f0b-4172-96fc-6aae259512ff)

**Additional context**  
works on Thia STG but not on Docs or Eurasia etc

**Comment by AmnestyAM** [comment] 2024-07-17 11:54
This is affecting some PRD sites who are using custom fonts 
![image](https://github.com/user-attachments/assets/e69ddaf1-34a6-4ed7-9c77-7a6e29d6ff4c)

**Comment by jaymcp** [comment] 2024-07-17 12:12
Duplicate of https://github.com/amnestywebsite/humanity-theme/issues/293
I've installed the new plugin on Eurasia STG.
Are there other sites using a Google font that will need the plugin?

**Comment by AmnestyAM** [comment] 2024-07-17 12:19
Ukraine and Israel (covered by the other ticket)

**Comment by jaymcp** [comment] 2024-07-17 12:21
I've installed the plugin on Ukraine STG.

**Comment by AmnestyAM** [comment] 2024-08-02 10:27
LGTM 
![image](https://github.com/user-attachments/assets/8a7dc01a-1409-47f6-b20f-b266192cb43e)
some new options :-)

**Closed** 2024-09-05 10:55 UTC
Labels: bug, UAT approved
