### ISSUE TITLE
Bug - Spacing on recently added / sidebar regressed 

### ISSUE THREAD

**Issue by AmnestyAM** [amnestywebsite/humanity-theme#307] opened 2024-07-18 16:06 UTC
![image](https://github.com/user-attachments/assets/20762a75-8848-4eb9-9c58-679820b8c972)

It now looks like this
https://www.amnesty.org/es/latest/news/2024/07/peru-muertes-lesiones-protestas-presidenta-cadena-mando-responsables-penales/

it should look more like this
![image](https://github.com/user-attachments/assets/3a6cf202-31cd-42dd-b8bf-1fc0b754f90f)

**Comment by jaymcp** [comment] 2024-07-19 10:55
duplicate of https://github.com/amnestywebsite/humanity-theme/issues/274

**Closed** 2024-07-26 08:58 UTC
Labels: bug
